language: cpp

sudo: required

env:
  global:
    - HXCPP_COMPILE_CACHE=~/hxcache

matrix:
  include:
    - os: linux
      dist: trusty
      env:
        - ARCH=32
      install:
        - bash tools/haxe/build_linux.sh
        - travis_retry sudo apt-get install gcc-multilib g++-multilib gdb -y;
    - os: linux
      dist: trusty
      env:
        - ARCH=64
      install:
        - bash tools/haxe/build_linux.sh
    - os: osx
      osx_image: xcode9.4
      env:
        - ARCH=32
      install:
        - bash tools/haxe/build_osx.sh;
    - os: osx
      osx_image: xcode9.4
      env:
        - ARCH=64
      install:
        - bash tools/haxe/build_osx.sh;

before_script:
- ulimit -c unlimited -S       # enable core dumps

after_failure:
- COREFILE=$(find . -maxdepth 1 -name "core*" | head -n 1) # find core file
- if [[ -f "$COREFILE" ]]; then gdb -c "$COREFILE" example -ex "thread apply all bt" -ex "set pagination 0" -batch; fi

script:
  - cd ${TRAVIS_BUILD_DIR}/tools/run
  - haxe compile.hxml
  - cd ${TRAVIS_BUILD_DIR}/tools/hxcpp
  - haxe compile.hxml
  - cd ${TRAVIS_BUILD_DIR}/project
  - haxe compile-cppia.hxml
  - cd ${TRAVIS_BUILD_DIR}/test
  - haxe --run RunTests cffi
  - haxe --run RunTests haxe
  - haxe --run RunTests telemetry
  - haxe --run RunTests std${ARCH}
  - haxe --run RunTests debugger
  - haxe --run RunTests native
  - cd ~/haxe/tests/unit
  - haxe compile-cpp.hxml -D HXCPP_M${ARCH} && ./bin/cpp/TestMain-debug
#
# Disable cppia tests, they fail with our branch :-(
#
# - haxe compile-cppia.hxml -debug && haxelib run hxcpp ./bin/unit.cppia
